# Generated by Django 4.0.5 on 2022-06-19 20:31

import django.contrib.postgres.fields
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields
from django.db import migrations, models

import dotfm.portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from=("title",)
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WIP", "Work in progress"),
                            ("PRODUCTION", "Production"),
                        ],
                        default="WIP",
                        max_length=30,
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status"
                    ),
                ),
                (
                    "tech_stack",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        default=dotfm.portfolio.models._default_tech_stack,
                        size=None,
                    ),
                ),
                ("github_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
