[tool.poetry]
name = "dotfm"
version = "0.1.0"
description = "Personal website"
authors = ["Tobi DEGNON <tobidegnon@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.4"
gunicorn = "^20.1.0"
psycopg2 = "^2.9.3"
django-fbv = "^0.4.0"
coltrane-web = "^0.18.2"
django-environ = "^0.8.1"
django-htmx = "^1.9.0"
procrastinate = "^0.24.1"
whitenoise = "^6.0.0"

[tool.poetry.dev-dependencies]
mypy = "^0.942"
black = "^22.3.0"
isort = "^5.10.1"
pytest = "^7.1.1"
poetryup = "^0.6.1"
django-browser-reload = "^1.3.0"
pywatchman = "^1.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
