[tool.poetry]
name = "dotfm"
version = "0.1.0"
description = "Personal website"
authors = ["Tobi DEGNON <tobidegnon@proton.me>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.5"
gunicorn = "^20.1.0"
psycopg2 = "2.9.3"
django-fbv = "^0.4.0"
django-environ = "^0.9.0"
django-htmx = "^1.12.0"
whitenoise = "^6.2.0"
django-tailwind = "^3.3.0"
django-model-utils = "^4.2.0"
django-lifecycle = "^1.0.0"
django-taggit = "^3.0.0"
django-extensions = "^3.1.5"
httpx = "^0.23.0"
django-pgtrigger = "^2.4.1"
markdown2 = "^2.4.3"

[tool.poetry.dev-dependencies]
django-browser-reload = "^1.6.0"
mypy = "^0.961"
black = "^22.3.0"
isort = "^5.10.1"
pytest = "^7.1.2"
poetryup = "^0.8.0"
pywatchman = "^1.4.1"
django-stubs = "^1.12.0"
pylint-django = "^2.5.3"
pre-commit = "^2.19.0"
ipython = "^8.4.0"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "config.settings"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
