# Generated by Django 4.1.2 on 2022-10-28 12:19

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("stack", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("web_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("featured", "-created", "-modified"),
            },
        ),
    ]
