# Generated by Django 4.1.2 on 2022-10-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("-featured", "-created", "-modified")},
        ),
        migrations.AddField(
            model_name="project",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
