# Generated by Django 4.1.2 on 2022-10-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("twitter", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("devto", models.URLField(blank=True)),
                ("hashnode", models.URLField(blank=True)),
                ("polywork", models.URLField(blank=True)),
                ("spotify", models.URLField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
