# Generated by Django 4.0.5 on 2022-06-20 09:05

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="content"
            ),
        ),
    ]
