# Generated by Django 4.1.1 on 2022-09-19 13:12

from django.db import migrations, models

import dotfm.blog.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="auto_publishing_date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="content_changed",
        ),
        migrations.RemoveField(
            model_name="post",
            name="private_key",
        ),
        migrations.RemoveField(
            model_name="post",
            name="published_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                max_length=255,
                unique=True,
                validators=[dotfm.blog.models._check_if_content_file_exists],
            ),
        ),
    ]
